version: 2.1
orbs:
  postgres-rspec: sbc-orbs/postgres-rspec@0.0.28
jobs:
  build:
    # working_directory: ~/myapp
    # docker:
    #   - image: circleci/ruby:2.7.1
    #     environment:
    #       DATABASE_URL: "postgres://myapp@localhost/myapp-test"
    #   - image: circleci/postgres:9.5-alpine
    #     environment:
    #       POSTGRES_USER: myapp
    #       POSTGRES_DB: myapp-test
    #       POSTGRES_PASSWORD: ""
    steps:
      - checkout

      - run:
          name: Bundle Install
          command: install

  #     - run:
  #         name: Wait for DB
  #         command: dockerize -wait tcp://localhost:5432 -timeout 1m

  #     - run:
  #         name: Database create 
  #         command: bin/rails db:create

  #     - run:
  #         name: Database setup
  #         command: bin/rails db:schema:load --trace

  #     - run:
  #         name: Run tests
  #         command: bin/rails rspec 

  #         orbs:
  # postgres-rspec: sbc-orbs/postgres-rspec@0.0.28
  # version: 2.1