version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.1
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Update bundler
          command: sudo gem update --system
      - run: 
          name: Update Ruby Version
          command:  bundle update --ruby
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/bundle-install
      - run: 
          name: Setup rails db
          command: rails:db:create 
      - run: 
          name: Setup rails migrations
          command: rails db:migrate 
      - run: 
          name: Test Suite
          command: bundle exec rspec

